name: bsit3bcrud
description: "A Flutter CRUD application for BSIT 3B with MySQL backend"

# Remove this line if you wish to publish to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # More flexible version constraint

dependencies:
  flutter:
    sdk: flutter

  # Essential packages for your CRUD app
  http: ^1.1.0           # For API calls (updated version)
  provider: ^6.1.1       # For state management (recommended addition)
  fluttertoast: ^8.2.2   # For toast notifications (alternative to SnackBar)
  intl: ^0.18.1          # For internationalization and date formatting
  cupertino_icons: ^1.0.8
  logger: ^1.1.0
  bcrypt: ^1.1.3
  shared_preferences: ^2.0.9
  image_picker: ^0.8.4+4
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and add these if you need assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Uncomment if you need custom fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700